version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
     - 28080:8080